#ifndef MAIN_H
#define MAIN_H
// Configuration des èparamtres du chip
#define FCY 60000000

#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_GAUCHE 4
#define STATE_TOURNE_GAUCHE_EN_COURS 5
#define STATE_TOURNE_DROITE_PLUS 6
#define STATE_TOURNE_DROITE_PLUS_EN_COURS 7
#define STATE_TOURNE_GAUCHE_PLUS  8 
#define STATE_TOURNE_GAUCHE_PLUS_EN_COURS 9
#define STATE_TOURNE_DROITE 10
#define STATE_TOURNE_DROITE_EN_COURS 11
#define STATE_TOURNE_SUR_PLACE_GAUCHE 12
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 13
#define STATE_TOURNE_SUR_PLACE_DROITE 14
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 15
#define STATE_ARRET 16
#define STATE_ARRET_EN_COURS 17
#define STATE_RECULE 18
#define STATE_RECULE_EN_COURS 19
#define PAS_D_OBSTACLE 0
#define OBSTACLE_A_GAUCHE 1
#define OBSTACLE_A_DROITE 2
#define OBSTACLE_EN_FACE 3
#define OBSTACLE_A_DROITE_PLUS 4
#define OBSTACLE_A_GAUCHE_PLUS 5
#define DIST_MAX 30.0
#define DIST_MAX_MID 30.0
// CONFIG 1 : ARRET 0 , STATE_VIT_AVANCE 25 STATE_VIT_RETOUR 15, TOURNER_SUR_PLACE_VIT 15, TOURNER_VIT 22,DIST_MAX 30.0
#define ARRET 0
#define STATE_VIT_AVANCE 27
#define TOURNER_SUR_PLACE_VIT 22
#define TOURNER_VIT 15



void determine_speeds();
int trigger(float capteur);
int trigger_mid(float capteur);
unsigned char CallCap();
void ADC_value();
void OperatingSystemLoop(void);
void SetNextRobotStateInAutomaticMode();
#endif /* ROBOT_H */